### ISSUE TITLE
Seg fault

### ISSUE THREAD

**Issue by trtr3104** [jursetta/Ursetta_CSCI2270_FinalProject#1]
Hello, I just cloned your project from your repo, and created a project out of your AdvancedComm.cpp, CommunicationNetwork.h, and CommunicationNetwork.cpp. The project runs just fine and displays the menu. However, whenever I try to select any option, it would result in a seg fault. For example, when I try to select option 1, it would display "Please clear the network before re-building.", and becomes a seg fault whenever I chose any other option. I've attached a screenshot below. It might just be on my end that maybe I am not running it correctly. Please let me know if there are any further steps I would have to take.
![virtualbox_cu-cs-vm-spring16-xfce-x64_03_05_2016_17_57_51](https://cloud.githubusercontent.com/assets/18508346/15001929/107f83ea-1159-11e6-91b5-6dd5c37585ff.png)

**Comment by jursetta** [comment]
Looks like the problem is in the CodeBlocks compiler. I built this program in Xcode which uses the apple LLMV compiler as apposed to the gcc compiler. Because of this, there are a few differences in memory allocation. The constructer in the CommunicationsNetwork.cpp file does not require an allocation of the head and tail of the linked list to NULL in Xcode, but it does in CodeBlocks. I was unaware of this until I spoke with a TA yesterday about the problem. I've uploaded the new cpp file so it should work, but please let me know if it does not. Thank you for the input.

**Comment by trtr3104** [comment]
Thank you for the update. Your code runs very smoothly. Great work!
